### PR TITLE
fixed spacing, started on breakable box. 

### PR DESCRIPTION
**Pull request by Zoroththeawesome**
spacing fixed with this verson. also added group for breakable box. need to give it health points and such still. for now, if you can just finish that and get the box to disappear when destroyed that'll be good enough until I can make some images for a breaking box. I will make images for rocket and flame thrower at the same time as the breaking box.

### CODE REVIEW

**Comment by Zoroththeawesome** [comment]
ps. game runs just like before in this code verson.

**Comment by Zoroththeawesome** [comment]
oh except I changed some damage values. grenade is now insta kill for enemies, makes the game faster paced. more of a shooter. only takes two shots to kill.

**Comment by Frankenmiller** [comment]
Appreciate your contributions Jacob, this is fun! 

Yo, we got look at this stuff carefully, that python_shooter.py file had my changes in it, and main_shooter.py file is not fully mine. His version is super slick and contains features in it that I'm going be adding to game engine I wrote but we shouldn't be using his code like it's ours. I wrote mine to have unique variable names like magazine_group to distinguish it

Now we have a "merge conflict" we need examine carefully... my changes were contained in python_shooter.py and your contributions are contained with in main_shooter. I will rework the project today, I won't delete the main_shooter file but the two must be combined and one eliminated so that focus just on one version

**Comment by Frankenmiller** [comment]
Merge conflict on this Pull request, please make note of any work done on main_shooter.py and copy paste them to python_shooter.py

Pull request closed 2022-JUL-16 by FRANKENMILLER

**Comment by Zoroththeawesome** [comment]
You told me this project was fully yours when I joined it. If it was taken from someone else's open-sourced work that is fine and we can build off it without having to make it complicated, but we need to give him credit for our starting position. This file would have merged into the main-shooter file with no conflicts, fixing the spacing problems so that I could edit the code. There were also 4 additional changes made to the code to add this new breakable box block. There is no reason for us to create a new verson entitled python_shooter and change more things to make it "ours". I think we need to find a time to zoom about this.

**Comment by Frankenmiller** [comment]
Sure, let’s discuss this. I’m putting together one my last commits of the session will add ‘Bulls-Eye” opening intro fade. I’ve edited and colorized some the png assets too, take a look closely.

I’ll be in front my computer next few hours working on some coursera stuff, just send over link we can get call started. Eager to hear your ideas Jacob

Bryan Allen Junior Software Developer
✉️ ***@***.***
📄 https://www.linkedin.com/in/frankenmiller
🧑🏽‍💻 https://github.com/frankenmiller
📊 public.tableau.com/app/profile/frankenmiller
📱 WhatsApp +264813643785

**Pull request closed without merging**
